dict={}
a=input("Enter your name : ")
b=input("Enter your favourite language: ")
dict.update({a:b})
a=input("Enter your name : ")
b=input("Enter your favourite language: ")
dict.update({a:b})
a=input("Enter your name : ")
b=input("Enter your favourite language: ")
dict.update({a:b})
a=input("Enter your name : ")
b=input("Enter your favourite language: ")
dict.update({a:b})
print(dict)