x=set()
n=input("Enter the number : ")
x.add(int(n))
n=input("Enter the number : ")
x.add(int(n))
n=input("Enter the number : ")
x.add(int(n))
n=input("Enter the number : ")
x.add(int(n))
n=input("Enter the number : ")
x.add(int(n))
n=input("Enter the number : ")
x.add(int(n))
n=input("Enter the number : ")
x.add(int(n))
n=input("Enter the number : ")
x.add(int(n))
print(x)